"""Fit, calibrate and persist NBA/WNBA V17 team-event specialists.

Raw sporting probabilities are generated by an independent basketball logistic
model using only pregame team performance/rest features. Market prices are not
features. Calibration reuses V17 phase_b_platt with chronological folds.

This pipeline never changes can_execute and never auto-promotes an artifact.
A successful run may advance certification state to SHADOW/CERTIFIED evidence,
but promoted/active remain false until an explicit certification replay promotes.
"""
from __future__ import annotations

import argparse
from dataclasses import asdict
from datetime import datetime, timezone
import json
import os
from typing import Any

import numpy as np

from basketball_team_event_specialist import (
    FEATURE_SCHEMA_VERSION,
    MODEL_FAMILY,
    TrainingGame,
    build_pregame_features,
    certification_decision,
    train_specialist,
    _fit_logistic,
    _sigmoid,
)
from calibration import phase_b_platt

can_execute: bool = False

TRAIN_TABLE = {"NBA": "wow_nba_training_games", "WNBA": "wow_wnba_training_games"}


def _client():
    from supabase import create_client
    key = os.getenv("SUPABASE_SERVICE_ROLE_KEY") or os.getenv("SUPABASE_SERVICE_KEY")
    if not key:
        raise RuntimeError("SUPABASE service credential unavailable")
    return create_client(os.environ["SUPABASE_URL"], key)


def load_games(client: Any, sport: str) -> list[TrainingGame]:
    sport = sport.upper()
    table = TRAIN_TABLE[sport]
    rows: list[dict[str, Any]] = []
    offset = 0
    while True:
        result = (
            client.table(table)
            .select("game_id,season,game_date,home_team_id,away_team_id,home_score,away_score")
            .eq("settled", True)
            .order("game_date")
            .range(offset, offset + 999)
            .execute()
        )
        batch = result.data or []
        rows.extend(batch)
        if len(batch) < 1000:
            break
        offset += 1000
    return [
        TrainingGame(
            game_id=str(r["game_id"]), sport=sport, season=int(r["season"]),
            game_date=datetime.fromisoformat(str(r["game_date"])).date(),
            home_team_id=str(r["home_team_id"]), away_team_id=str(r["away_team_id"]),
            home_score=int(r["home_score"]), away_score=int(r["away_score"]),
        )
        for r in rows
    ]


def _walk_forward_raw(rows, *, burn_in: int = 150, folds: int = 6):
    """Generate strictly out-of-time raw probabilities for V17 calibration."""
    if len(rows) < burn_in + 200:
        raise ValueError(f"walk-forward calibration requires >= {burn_in + 200} usable rows; got {len(rows)}")
    evaluation = list(rows[burn_in:])
    fold_bounds = np.array_split(np.arange(len(evaluation)), folds)
    raw_probs: list[float] = []
    outcomes: list[int] = []
    fold_ids: list[int] = []
    timestamps: list[str] = []
    for fold_id, positions in enumerate(fold_bounds):
        if not len(positions):
            continue
        first_global = burn_in + int(positions[0])
        train = list(rows[:first_global])
        x_train = np.asarray([r.values for r in train], dtype=float)
        y_train = np.asarray([r.outcome for r in train], dtype=float)
        means = x_train.mean(axis=0)
        scales = x_train.std(axis=0)
        scales[scales < 1e-9] = 1.0
        intercept, beta = _fit_logistic((x_train - means) / scales, y_train)
        for pos in positions:
            row = evaluation[int(pos)]
            x = (np.asarray(row.values, dtype=float) - means) / scales
            raw_probs.append(float(_sigmoid(intercept + x @ beta)))
            outcomes.append(int(row.outcome))
            fold_ids.append(fold_id)
            timestamps.append(datetime.combine(row.game_date, datetime.min.time(), tzinfo=timezone.utc).isoformat())
    return raw_probs, outcomes, fold_ids, timestamps


def fit_and_persist(sport: str, client=None) -> dict[str, Any]:
    sport = sport.upper()
    if sport not in TRAIN_TABLE:
        raise ValueError(f"unsupported sport {sport}")
    client = client or _client()
    games = load_games(client, sport)
    features = build_pregame_features(games, sport)
    version_stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    model_version = f"{sport}_TEAM_EVENT_LOGISTIC_V1_{version_stamp}"
    artifact = train_specialist(features, sport, model_artifact_version=model_version)

    raw, outcomes, folds, timestamps = _walk_forward_raw(features)
    calibration = phase_b_platt(raw, outcomes, folds, timestamps)
    calibration_status = calibration.result.calibration_status if calibration.result is not None else None
    decision = certification_decision(
        artifact, sport=sport, calibration_rows=len(raw),
        calibration_status=calibration_status, provenance_complete=True,
    )
    calibrator_version = f"{sport}_TEAM_EVENT_PLATT_V1_{version_stamp}"

    artifact_payload = asdict(artifact)
    client.table("wow_basketball_team_event_model_artifacts").insert({
        "sport": sport,
        "model_family": MODEL_FAMILY,
        "model_artifact_version": model_version,
        "feature_schema_version": FEATURE_SCHEMA_VERSION,
        "artifact_format": "WOW_BASKETBALL_LOGISTIC_JSON_V1",
        "artifact_payload": artifact_payload,
        "artifact_checksum": artifact.artifact_checksum,
        "training_row_count": artifact.training_row_count,
        "train_start_date": artifact.train_start_date,
        "train_end_date": artifact.train_end_date,
        "holdout_row_count": artifact.holdout_row_count,
        "holdout_brier": artifact.holdout_brier,
        "holdout_log_loss": artifact.holdout_log_loss,
        "holdout_accuracy": artifact.holdout_accuracy,
        "promoted": False,
        "active": False,
    }).execute()

    client.table("wow_basketball_team_event_calibrators").insert({
        "sport": sport,
        "calibrator_version": calibrator_version,
        "model_artifact_version": model_version,
        "calibration_method": calibration_status or "PLATT_TIME_SPLIT_V1_BLOCKED",
        "coefficients": {"a": calibration.coefficients.a, "b": calibration.coefficients.b},
        "calibration_row_count": len(raw),
        "brier": calibration.metrics.brier,
        "log_loss": calibration.metrics.log_loss,
        "ece": calibration.metrics.ece,
        "calibration_bias": calibration.metrics.calibration_bias,
        "promoted": False,
        "active": False,
    }).execute()

    client.table("wow_basketball_team_event_certification").upsert({
        "sport": sport,
        "capability_status": "SHADOW" if decision.capability_status == "CERTIFIED" else decision.capability_status,
        "reason_code": "CERTIFICATION_REPLAY_REQUIRED" if decision.capability_status == "CERTIFIED" else decision.reason_code,
        "model_artifact_version": model_version,
        "calibrator_version": calibrator_version,
        "corpus_rows": len(games),
        "settled_rows": len(games),
        "certification_notes": {
            "fit_decision": asdict(decision),
            "calibration_status": calibration_status,
            "promotion_attempted": False,
            "can_execute": False,
        },
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }, on_conflict="sport").execute()

    return {
        "sport": sport,
        "corpus_rows": len(games),
        "feature_rows": len(features),
        "model_artifact_version": model_version,
        "calibrator_version": calibrator_version,
        "holdout_brier": artifact.holdout_brier,
        "holdout_log_loss": artifact.holdout_log_loss,
        "holdout_accuracy": artifact.holdout_accuracy,
        "calibration_rows": len(raw),
        "calibration_status": calibration_status,
        "fit_decision": asdict(decision),
        "persisted_status": "SHADOW" if decision.capability_status == "CERTIFIED" else decision.capability_status,
        "promotion_attempted": False,
        "can_execute": False,
    }


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--sport", choices=["NBA", "WNBA"], required=True)
    args = p.parse_args()
    print(json.dumps(fit_and_persist(args.sport), sort_keys=True))


if __name__ == "__main__":
    main()
