from nfl_prop_auto_hydration import STAT_CONFIG,STAT_ALIASES,PROVIDER_ID
def test_bounded_routes():
    assert set(STAT_CONFIG)=={'PASSING_YARDS','RUSHING_YARDS','RECEIVING_YARDS','ANYTIME_TD'}
    assert STAT_ALIASES['PASS_YARDS']=='PASSING_YARDS'; assert STAT_ALIASES['RUSH_YARDS']=='RUSHING_YARDS'; assert STAT_ALIASES['ANYTIME_TDS']=='ANYTIME_TD'
    assert PROVIDER_ID=='NFL_ESPN_IDENTITY_NFLVERSE_STATS_V1'
