from enum import Enum


class PropLabel(str, Enum):
    RESEARCH_INTEREST        = "RESEARCH_INTEREST"
    MODEL_QUALIFIED_HOLD     = "MODEL_QUALIFIED_HOLD"
    MARKET_VERIFIED_HOLD     = "MARKET_VERIFIED_HOLD"
    MONEY_QUALIFIED          = "MONEY_QUALIFIED"
    FINAL_APPROVED           = "FINAL_APPROVED"
    REJECT_NO_EDGE           = "REJECT_NO_EDGE"
    REJECT_BAD_STRUCTURE     = "REJECT_BAD_STRUCTURE"
    REJECT_DATA_QUALITY      = "REJECT_DATA_QUALITY"
    SOURCE_CONFLICT          = "SOURCE_CONFLICT"
    SLATE_PURGE              = "SLATE_PURGE"
    DUPLICATE_EXPOSURE_BLOCK = "DUPLICATE_EXPOSURE_BLOCK"
    NO_PLAY                  = "NO_PLAY"
    # Module B — Data Contract
    DATA_CONTRACT_FAIL                  = "DATA_CONTRACT_FAIL"
    # Module C — Payout Context
    MARKET_QUALIFIED_BUT_SLIP_NEGATIVE  = "MARKET_QUALIFIED_BUT_SLIP_NEGATIVE"
    FORMAT_PENDING                      = "FORMAT_PENDING"
    # Module G — Directional Exposure
    DIRECTIONAL_EXPOSURE_BLOCK          = "DIRECTIONAL_EXPOSURE_BLOCK"
    SESSION_EXPOSURE_WARNING            = "SESSION_EXPOSURE_WARNING"
    SESSION_DIRECTIONAL_EXPOSURE_BLOCK  = "SESSION_DIRECTIONAL_EXPOSURE_BLOCK"
    # Patch 2026-06-27 — Sharp Market Anchor (directional)
    REJECT_SHARP_CONFLICT               = "REJECT_SHARP_CONFLICT"
    REJECT_FALLING_KNIFE                = "REJECT_FALLING_KNIFE"
    FLIP_CANDIDATE                      = "FLIP_CANDIDATE"
    # Patch 2026-06-27 — House Rules Matrix
    REJECT_HOUSE_RULES_VULNERABILITY    = "REJECT_HOUSE_RULES_VULNERABILITY"
    HOUSE_RULES_CAUTION                 = "HOUSE_RULES_CAUTION"
    # Patch 2026-06-27 — Execution Friction Gate
    REJECT_EXECUTION_STALE              = "REJECT_EXECUTION_STALE"
    REJECT_PAYOUT_CHANGED               = "REJECT_PAYOUT_CHANGED"
    REJECT_LOW_LIQUIDITY                = "REJECT_LOW_LIQUIDITY"
    REJECT_LINE_MOVED_AGAINST_SIDE      = "REJECT_LINE_MOVED_AGAINST_SIDE"
    # Patch 2026-06-27 — Settlement Loopback
    CALIBRATION_STALE_HOLD              = "CALIBRATION_STALE_HOLD"
    # Patch 2026-06-27 — Correlation Gate
    REJECT_POWER_CORRELATED             = "REJECT_POWER_CORRELATED"
    # Phase 1 2026-07-07 — Degraded Engine Run
    DEGRADED_ENGINE_RUN                 = "DEGRADED_ENGINE_RUN"
    # WOW-PATCH-2026-07-10 — Combo & Settlement Governance
    HARD_REJECT_COMBO_MULTIPLICATION    = "HARD_REJECT_COMBO_MULTIPLICATION"
    SETTLEMENT_SOURCE_CONFLICT          = "SETTLEMENT_SOURCE_CONFLICT"
    SERIES_STATE_CAUTION                = "SERIES_STATE_CAUTION"
    # WOW-PATCH-MANDATORY-RECONSTRUCTION-v1.0 — Acquisition enforcement
    RUN_INVALID_ACQUISITION_INCOMPLETE      = "RUN_INVALID — ACQUISITION_INCOMPLETE"
    INPUT_FAILURE_ACQUISITION_NOT_COMPLETED = "INPUT_FAILURE — ACQUISITION_NOT_COMPLETED"
    # WOW-PATCH-2026-07-15 — Prop Calibration, Exposure & Slip Governance
    REJECT_MARKET_ADVERSE_THRESHOLD         = "REJECT_MARKET_ADVERSE_THRESHOLD"
    REJECT_MARKET_ADVERSE_PUSH_LOSS         = "REJECT_MARKET_ADVERSE_PUSH_LOSS"
    COMPONENT_COMPOSITE_CONFLICT            = "COMPONENT_COMPOSITE_CONFLICT"
    REJECT_CONTRADICTORY_ROLE_STATE         = "REJECT_CONTRADICTORY_ROLE_STATE"
    REJECT_OPPORTUNITY_SUM_MISMATCH         = "REJECT_OPPORTUNITY_SUM_MISMATCH"
    HIGH_CONFIDENCE_SUSPENDED               = "HIGH_CONFIDENCE_SUSPENDED_CALIBRATION_FAILURE"
    RUN_INVALID_GOVERNANCE_MISMATCH         = "RUN_INVALID_GOVERNANCE_MISMATCH"
    PREDICTION_MARKET_SOURCE_CEILING        = "PREDICTION_MARKET_SOURCE_CEILING"
    # LLP MLB Winner Preflight Gate (reviewer-mandated, PATCH-LEVEL REQUIRED)
    MLB_WINNER_PREFLIGHT_BLOCK              = "MLB_WINNER_PREFLIGHT_BLOCK"


class DataStatus(str, Enum):
    RETRIEVED        = "RETRIEVED"
    RECONSTRUCTED    = "RECONSTRUCTED"
    PROXY_ONLY       = "PROXY_ONLY"
    FAILED           = "FAILED"
    SOURCE_CONFLICT  = "SOURCE_CONFLICT"
    INPUT_FAILURE    = "INPUT_FAILURE"
    DATA_UNOBTAINABLE = "DATA_UNOBTAINABLE"
    NOT_CALLED       = "NOT_CALLED"


APPROVAL_LABELS = {PropLabel.FINAL_APPROVED, PropLabel.MONEY_QUALIFIED}
REJECT_LABELS   = {
    PropLabel.REJECT_NO_EDGE,
    PropLabel.REJECT_BAD_STRUCTURE,
    PropLabel.REJECT_DATA_QUALITY,
    PropLabel.SOURCE_CONFLICT,
    PropLabel.SLATE_PURGE,
    PropLabel.DUPLICATE_EXPOSURE_BLOCK,
    PropLabel.NO_PLAY,
    # Patch 2026-06-27
    PropLabel.REJECT_SHARP_CONFLICT,
    PropLabel.REJECT_FALLING_KNIFE,
    PropLabel.REJECT_HOUSE_RULES_VULNERABILITY,
    PropLabel.REJECT_EXECUTION_STALE,
    PropLabel.REJECT_PAYOUT_CHANGED,
    PropLabel.REJECT_LOW_LIQUIDITY,
    PropLabel.REJECT_LINE_MOVED_AGAINST_SIDE,
    PropLabel.REJECT_POWER_CORRELATED,
    PropLabel.DEGRADED_ENGINE_RUN,
    # LLP MLB Winner Preflight Gate
    PropLabel.MLB_WINNER_PREFLIGHT_BLOCK,
}

GATE_ORDER = [
    "board_intake",
    "slate_validation",
    "status_role",
    "l5_l10_ledger",
    "outlier_gate",
    "market_gate",
    "sharp_anchor",
    "house_rules",
    "ev_gate",
    "slip_structure",
    "exposure_gate",
    "classifier",
]


# Correlation classification labels (sub-labels inside sharp_anchor / payout_context)
class CorrelationClass(str, Enum):
    DIRECT_OVERLAP              = "DIRECT_OVERLAP"
    SAME_PLAYER_COMPONENT       = "SAME_PLAYER_COMPONENT_OVERLAP"
    TEAMMATE_USAGE_NEGATIVE     = "TEAMMATE_USAGE_NEGATIVE"
    TEAMMATE_USAGE_POSITIVE     = "TEAMMATE_USAGE_POSITIVE"
    PACE_ENVIRONMENT_POSITIVE   = "PACE_ENVIRONMENT_POSITIVE"
    BLOWOUT_SHARED_RISK         = "BLOWOUT_SHARED_RISK"
    INJURY_ROLE_DEPENDENCY      = "INJURY_ROLE_DEPENDENCY"
    LOW_CORRELATION             = "LOW_CORRELATION"
    UNKNOWN                     = "CORRELATION_UNKNOWN"
