"""Static inventory of V17 certified MLB prop families for route QA.

This is declarative QA metadata only. It does not score, recommend, or execute.
"""

CERTIFIED_MLB_PROP_FAMILIES = {
    "PITCHER_STRIKEOUTS": "MLB_PITCHER_SO_FAILURE_PATH_NB_V1",
    "1ST_INNING_PITCHES_THROWN": "MLB_1IP_CONDITIONAL_TOTAL_PITCH_PMF_V1",
    "PITCHING_OUTS": "MLB_PITCHER_OUTS_WORKLOAD_NB_V1",
    "STRIKES_THROWN": "MLB_PITCHER_STRIKES_THROWN_WORKLOAD_NB_V1",
    "BALLS_THROWN": "MLB_PITCHER_BALLS_THROWN_WORKLOAD_NB_V1",
    "PLATE_APPEARANCES": "MLB_BATTER_PLATE_APPEARANCES_NB_V1",
}
