"""
storage/daily_manifest.py — Immutable WOW Daily Run Manifest

Provides persistent, idempotent storage for canonical WOW Daily run records.

Tables
------
wow_daily_runs        — one row per canonical daily run (run_id PK)
wow_daily_run_rows    — one row per evaluated selection in a run

Design invariants
-----------------
- run_id is a UUID generated by the orchestrator before any evaluation begins.
- Rows are written once, never updated.  Reconciliation state is appended-only.
- A duplicate run_id write is an idempotent no-op (ON CONFLICT DO NOTHING).
- No selection write succeeds without a matching run header.
- can_execute = False (dry-run module; actual writes are driven by the route).
"""
from __future__ import annotations

import json
import os
import logging
import threading
from datetime import date, datetime, timezone
from typing import Any

import psycopg2

logger = logging.getLogger(__name__)

can_execute = False
MODULE_ID = "WOW-DAILY-MANIFEST-v1.0"
_DB_CONNECT_TIMEOUT_SECONDS = 5
_DB_STATEMENT_TIMEOUT_MS = 30_000
_DB_LOCK_TIMEOUT_MS = 5_000
_ACK_CONNECT_TIMEOUT_SECONDS = 2
_ACK_STATEMENT_TIMEOUT_MS = 3_000
_ACK_LOCK_TIMEOUT_MS = 1_000
_SCHEMA_ADVISORY_LOCK = 441_721_908
_schema_ready = False
_schema_lock = threading.Lock()

# ---------------------------------------------------------------------------
# DB connection helper (mirrors storage/results.py pattern)
# ---------------------------------------------------------------------------

def _get_conn(*, acknowledgement: bool = False):
    url = os.environ.get("DATABASE_URL", "")
    if not url:
        raise RuntimeError("DATABASE_URL not set")
    connect_timeout = (
        _ACK_CONNECT_TIMEOUT_SECONDS
        if acknowledgement else _DB_CONNECT_TIMEOUT_SECONDS
    )
    statement_timeout = (
        _ACK_STATEMENT_TIMEOUT_MS
        if acknowledgement else _DB_STATEMENT_TIMEOUT_MS
    )
    lock_timeout = (
        _ACK_LOCK_TIMEOUT_MS
        if acknowledgement else _DB_LOCK_TIMEOUT_MS
    )
    return psycopg2.connect(
        url,
        connect_timeout=connect_timeout,
        options=(
            f"-c statement_timeout={statement_timeout} "
            f"-c lock_timeout={lock_timeout}"
        ),
    )


# ---------------------------------------------------------------------------
# Schema bootstrap
# ---------------------------------------------------------------------------

_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS wow_daily_runs (
    run_id              TEXT PRIMARY KEY,
    run_date            DATE        NOT NULL,
    started_at          TIMESTAMPTZ NOT NULL,
    finished_at         TIMESTAMPTZ,
    environment         TEXT        NOT NULL DEFAULT 'live',
    requested_sports    JSONB       NOT NULL DEFAULT '[]',
    scanned_sports      JSONB       NOT NULL DEFAULT '[]',
    missing_sports      JSONB       NOT NULL DEFAULT '[]',
    run_status          TEXT        NOT NULL DEFAULT 'IN_PROGRESS',
    failed_modules      JSONB       NOT NULL DEFAULT '[]',
    runtime_provenance  JSONB,
    source_union_counts JSONB,
    total_discovered    INTEGER     NOT NULL DEFAULT 0,
    reconciliation      JSONB,
    session_id          TEXT,
    idempotency_key     TEXT,
    deadline_at         TIMESTAMPTZ,
    progress_stage      TEXT        NOT NULL DEFAULT 'ACCEPTED',
    progress_detail     TEXT,
    progress_updated_at TIMESTAMPTZ,
    failure_reason      TEXT,
    failure_module      TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS wow_daily_run_rows (
    id                      SERIAL PRIMARY KEY,
    run_id                  TEXT        NOT NULL REFERENCES wow_daily_runs(run_id),
    canonical_selection_id  TEXT        NOT NULL,
    market_version_id       TEXT,
    run_date                DATE        NOT NULL,
    sport                   TEXT        NOT NULL,
    player                  TEXT        NOT NULL,
    prop                    TEXT        NOT NULL,
    side                    TEXT        NOT NULL,
    line                    REAL        NOT NULL,
    game_date               TEXT,
    terminal_bucket         TEXT,
    classification          TEXT,
    wow_score               REAL,
    final_approval_blocker  TEXT,
    audit_valid             BOOLEAN,
    side_resolution         TEXT,
    reconciliation_status   TEXT,
    full_row                JSONB,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (run_id, canonical_selection_id)
);

CREATE INDEX IF NOT EXISTS idx_wow_daily_runs_date ON wow_daily_runs(run_date);
CREATE INDEX IF NOT EXISTS idx_wow_daily_run_rows_run_id ON wow_daily_run_rows(run_id);
CREATE INDEX IF NOT EXISTS idx_wow_daily_run_rows_sel_id ON wow_daily_run_rows(canonical_selection_id);
"""


def ensure_tables() -> bool:
    """Create manifest tables once per process with cross-worker DDL safety."""
    global _schema_ready
    if _schema_ready:
        return True

    with _schema_lock:
        if _schema_ready:
            return True
        try:
            conn = _get_conn()
            with conn:
                with conn.cursor() as cur:
                    # DDL is only a bootstrap concern. Serialize it across
                    # gunicorn/process workers so duplicate POSTs never
                    # deadlock before their idempotency record is read.
                    cur.execute(
                        "SELECT pg_advisory_xact_lock(%s)",
                        (_SCHEMA_ADVISORY_LOCK,),
                    )
                    cur.execute(_SCHEMA_SQL)
                    cur.execute(
                        """
                        ALTER TABLE wow_daily_runs
                            ADD COLUMN IF NOT EXISTS idempotency_key TEXT,
                            ADD COLUMN IF NOT EXISTS deadline_at TIMESTAMPTZ,
                            ADD COLUMN IF NOT EXISTS progress_stage TEXT
                                NOT NULL DEFAULT 'ACCEPTED',
                            ADD COLUMN IF NOT EXISTS progress_detail TEXT,
                            ADD COLUMN IF NOT EXISTS progress_updated_at TIMESTAMPTZ,
                            ADD COLUMN IF NOT EXISTS failure_reason TEXT,
                            ADD COLUMN IF NOT EXISTS failure_module TEXT
                        """
                    )
                    cur.execute(
                        """
                        CREATE UNIQUE INDEX IF NOT EXISTS
                            uq_wow_daily_runs_idempotency_key
                        ON wow_daily_runs (idempotency_key)
                        WHERE idempotency_key IS NOT NULL
                        """
                    )
            conn.close()
            _schema_ready = True
            return True
        except Exception as exc:
            logger.error("daily_manifest.ensure_tables failed: %s", exc)
            return False


# ---------------------------------------------------------------------------
# Run header
# ---------------------------------------------------------------------------

def create_run(
    *,
    run_id: str,
    run_date: str,
    started_at: str,
    environment: str,
    requested_sports: list[str],
    session_id: str | None = None,
    runtime_provenance: dict | None = None,
) -> bool:
    """
    Insert the run header row.  Idempotent — duplicate run_id is a no-op.
    Returns True on success, False on failure.
    """
    try:
        conn = _get_conn()
        with conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO wow_daily_runs
                        (run_id, run_date, started_at, environment,
                         requested_sports, session_id, runtime_provenance)
                    VALUES (%s, %s, %s, %s, %s, %s, %s)
                    ON CONFLICT (run_id) DO NOTHING
                    """,
                    (
                        run_id,
                        run_date,
                        started_at,
                        environment,
                        json.dumps(requested_sports),
                        session_id,
                        json.dumps(runtime_provenance) if runtime_provenance else None,
                    ),
                )
        conn.close()
        return True
    except Exception as exc:
        logger.error("daily_manifest.create_run failed for %s: %s", run_id, exc)
        return False


def _decode_run_row(row: dict[str, Any]) -> dict[str, Any]:
    for key in (
        "requested_sports", "scanned_sports", "missing_sports",
        "failed_modules", "runtime_provenance", "source_union_counts",
        "reconciliation",
    ):
        if isinstance(row.get(key), str):
            try:
                row[key] = json.loads(row[key])
            except Exception:
                pass
    return row


def create_or_get_run(
    *,
    run_id: str,
    idempotency_key: str | None,
    run_date: str,
    started_at: str,
    deadline_at: str,
    environment: str,
    requested_sports: list[str] | None,
    session_id: str | None = None,
    runtime_provenance: dict | None = None,
) -> tuple[dict[str, Any] | None, bool]:
    """Atomically create or reuse one canonical run identity."""
    conn = _get_conn(acknowledgement=True)
    try:
        with conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO wow_daily_runs (
                        run_id, run_date, started_at, environment,
                        requested_sports, session_id, runtime_provenance,
                        idempotency_key, deadline_at,
                        run_status, progress_stage, progress_updated_at
                    ) VALUES (
                        %s, %s, %s, %s, %s, %s, %s,
                        %s, %s, 'ACCEPTED', 'ACCEPTED', NOW()
                    )
                    ON CONFLICT DO NOTHING
                    RETURNING run_id
                    """,
                    (
                        run_id,
                        run_date,
                        started_at,
                        environment,
                        json.dumps(requested_sports or []),
                        session_id,
                        json.dumps(runtime_provenance)
                        if runtime_provenance else None,
                        idempotency_key,
                        deadline_at,
                    ),
                )
                created = cur.fetchone() is not None
                if idempotency_key:
                    cur.execute(
                        "SELECT * FROM wow_daily_runs "
                        "WHERE idempotency_key = %s LIMIT 1",
                        (idempotency_key,),
                    )
                else:
                    cur.execute(
                        "SELECT * FROM wow_daily_runs "
                        "WHERE run_id = %s LIMIT 1",
                        (run_id,),
                    )
                cols = [d[0] for d in cur.description]
                row = cur.fetchone()
        return (
            _decode_run_row(dict(zip(cols, row))) if row else None,
            created,
        )
    finally:
        conn.close()


def claim_run(run_id: str) -> bool:
    """Claim an accepted run exactly once across workers."""
    conn = _get_conn(acknowledgement=True)
    try:
        with conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    UPDATE wow_daily_runs
                    SET run_status = 'IN_PROGRESS',
                        progress_stage = 'STARTING',
                        progress_detail = 'Worker claimed run',
                        progress_updated_at = NOW()
                    WHERE run_id = %s
                      AND run_status = 'ACCEPTED'
                      AND finished_at IS NULL
                    """,
                    (run_id,),
                )
                return cur.rowcount == 1
    finally:
        conn.close()


def mark_progress(
    *,
    run_id: str,
    stage: str,
    detail: str | None = None,
) -> bool:
    """Persist lifecycle progress without changing scoring or row semantics."""
    conn = _get_conn()
    try:
        with conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    UPDATE wow_daily_runs
                    SET progress_stage = %s,
                        progress_detail = %s,
                        progress_updated_at = NOW()
                    WHERE run_id = %s
                      AND finished_at IS NULL
                      AND run_status IN ('ACCEPTED', 'IN_PROGRESS')
                    """,
                    (stage, detail, run_id),
                )
                return cur.rowcount == 1
    finally:
        conn.close()


def terminalize_run(
    *,
    run_id: str,
    finished_at: str,
    run_status: str,
    failure_reason: str | None = None,
    failure_module: str | None = None,
    reconciliation: dict | None = None,
) -> bool:
    """Close an accepted/in-progress run exactly once."""
    conn = _get_conn()
    try:
        with conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    UPDATE wow_daily_runs
                    SET finished_at = %s,
                        run_status = %s,
                        progress_stage = 'TERMINAL',
                        progress_detail = %s,
                        progress_updated_at = NOW(),
                        failure_reason = %s,
                        failure_module = %s,
                        reconciliation = COALESCE(%s, reconciliation)
                    WHERE run_id = %s
                      AND finished_at IS NULL
                      AND run_status IN ('ACCEPTED', 'IN_PROGRESS')
                    """,
                    (
                        finished_at,
                        run_status,
                        failure_reason or run_status,
                        failure_reason,
                        failure_module,
                        json.dumps(reconciliation)
                        if reconciliation is not None else None,
                        run_id,
                    ),
                )
                return cur.rowcount == 1
    finally:
        conn.close()


def reap_expired_runs(*, now: str) -> int:
    """Fail-closed stale accepted/running headers on the next lifecycle call."""
    conn = _get_conn()
    try:
        with conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    UPDATE wow_daily_runs
                    SET finished_at = %s,
                        run_status = 'DEGRADED',
                        progress_stage = 'TERMINAL',
                        progress_detail = 'Deadline/orphan reaper',
                        progress_updated_at = NOW(),
                        failure_reason = 'WHOLE_RUN_DEADLINE_EXCEEDED',
                        failure_module = 'daily_manifest.reap_expired_runs'
                    WHERE finished_at IS NULL
                      AND run_status IN ('ACCEPTED', 'IN_PROGRESS')
                      AND deadline_at IS NOT NULL
                      AND deadline_at < %s
                    """,
                    (now, now),
                )
                return cur.rowcount
    finally:
        conn.close()


def finalize_run(
    *,
    run_id: str,
    finished_at: str,
    run_status: str,
    scanned_sports: list[str],
    missing_sports: list[str],
    failed_modules: list[str],
    total_discovered: int,
    source_union_counts: dict,
    reconciliation: dict,
) -> bool:
    """Update run header with final state. Called after all rows are written."""
    try:
        conn = _get_conn()
        with conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    UPDATE wow_daily_runs SET
                        finished_at         = %s,
                        run_status          = %s,
                        scanned_sports      = %s,
                        missing_sports      = %s,
                        failed_modules      = %s,
                        total_discovered    = %s,
                        source_union_counts = %s,
                        reconciliation      = %s,
                        progress_stage      = 'TERMINAL',
                        progress_detail     = %s,
                        progress_updated_at = NOW()
                    WHERE run_id = %s
                      AND finished_at IS NULL
                      AND run_status IN ('ACCEPTED', 'IN_PROGRESS')
                    """,
                    (
                        finished_at,
                        run_status,
                        json.dumps(scanned_sports),
                        json.dumps(missing_sports),
                        json.dumps(failed_modules),
                        total_discovered,
                        json.dumps(source_union_counts),
                        json.dumps(reconciliation),
                        run_status,
                        run_id,
                    ),
                )
        conn.close()
        return True
    except Exception as exc:
        logger.error("daily_manifest.finalize_run failed for %s: %s", run_id, exc)
        return False


# ---------------------------------------------------------------------------
# Selection rows
# ---------------------------------------------------------------------------

def save_run_row(
    *,
    run_id: str,
    canonical_selection_id: str,
    market_version_id: str | None,
    run_date: str,
    sport: str,
    player: str,
    prop: str,
    side: str,
    line: float,
    game_date: str | None,
    terminal_bucket: str | None,
    classification: str | None,
    wow_score: float | None,
    final_approval_blocker: str | None,
    audit_valid: bool | None,
    side_resolution: str | None,
    reconciliation_status: str | None,
    full_row: dict,
) -> bool:
    """
    Persist one evaluated selection row.  Idempotent on (run_id, canonical_selection_id).
    Returns True on success.
    """
    try:
        conn = _get_conn()
        with conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO wow_daily_run_rows (
                        run_id, canonical_selection_id, market_version_id,
                        run_date, sport, player, prop, side, line, game_date,
                        terminal_bucket, classification, wow_score,
                        final_approval_blocker, audit_valid, side_resolution,
                        reconciliation_status, full_row
                    ) VALUES (
                        %s, %s, %s,
                        %s, %s, %s, %s, %s, %s, %s,
                        %s, %s, %s,
                        %s, %s, %s,
                        %s, %s
                    )
                    ON CONFLICT (run_id, canonical_selection_id) DO NOTHING
                    """,
                    (
                        run_id, canonical_selection_id, market_version_id,
                        run_date, sport, player, prop, side, line, game_date,
                        terminal_bucket, classification, wow_score,
                        final_approval_blocker, audit_valid, side_resolution,
                        reconciliation_status, json.dumps(full_row, default=str),
                    ),
                )
        conn.close()
        return True
    except Exception as exc:
        logger.error(
            "daily_manifest.save_run_row failed run=%s sel=%s: %s",
            run_id, canonical_selection_id, exc,
        )
        return False


# ---------------------------------------------------------------------------
# Read helpers
# ---------------------------------------------------------------------------

def get_run(run_id: str) -> dict | None:
    """Fetch run header by run_id. Returns None when not found."""
    try:
        conn = _get_conn()
        with conn.cursor() as cur:
            cur.execute(
                "SELECT * FROM wow_daily_runs WHERE run_id = %s LIMIT 1",
                (run_id,),
            )
            cols = [d[0] for d in cur.description]
            row = cur.fetchone()
        conn.close()
        if row is None:
            return None
        result = dict(zip(cols, row))
        for k in ("requested_sports", "scanned_sports", "missing_sports",
                  "failed_modules", "runtime_provenance", "source_union_counts",
                  "reconciliation"):
            if isinstance(result.get(k), str):
                try:
                    result[k] = json.loads(result[k])
                except Exception:
                    pass
        return result
    except Exception as exc:
        logger.error("daily_manifest.get_run failed for %s: %s", run_id, exc)
        return None


def get_run_rows(run_id: str, limit: int = 500) -> list[dict]:
    """Fetch all evaluated rows for a run. Returns [] on failure."""
    try:
        conn = _get_conn()
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT run_id, canonical_selection_id, market_version_id,
                       sport, player, prop, side, line, game_date,
                       terminal_bucket, classification, wow_score,
                       final_approval_blocker, audit_valid, side_resolution,
                       reconciliation_status, created_at
                FROM wow_daily_run_rows
                WHERE run_id = %s
                ORDER BY sport, player, prop, side
                LIMIT %s
                """,
                (run_id, limit),
            )
            cols = [d[0] for d in cur.description]
            rows = [dict(zip(cols, r)) for r in cur.fetchall()]
        conn.close()
        return rows
    except Exception as exc:
        logger.error("daily_manifest.get_run_rows failed for %s: %s", run_id, exc)
        return []


def list_runs(run_date: str | None = None, limit: int = 10) -> list[dict]:
    """List recent run headers. Optionally filter by date."""
    try:
        conn = _get_conn()
        with conn.cursor() as cur:
            if run_date:
                cur.execute(
                    """
                    SELECT run_id, run_date, started_at, finished_at,
                           environment, run_status, total_discovered,
                           requested_sports, scanned_sports, missing_sports
                    FROM wow_daily_runs
                    WHERE run_date = %s
                    ORDER BY started_at DESC LIMIT %s
                    """,
                    (run_date, limit),
                )
            else:
                cur.execute(
                    """
                    SELECT run_id, run_date, started_at, finished_at,
                           environment, run_status, total_discovered,
                           requested_sports, scanned_sports, missing_sports
                    FROM wow_daily_runs
                    ORDER BY started_at DESC LIMIT %s
                    """,
                    (limit,),
                )
            cols = [d[0] for d in cur.description]
            rows = [dict(zip(cols, r)) for r in cur.fetchall()]
        conn.close()
        for r in rows:
            for k in ("requested_sports", "scanned_sports", "missing_sports"):
                if isinstance(r.get(k), str):
                    try:
                        r[k] = json.loads(r[k])
                    except Exception:
                        pass
        return rows
    except Exception as exc:
        logger.error("daily_manifest.list_runs failed: %s", exc)
        return []


# ---------------------------------------------------------------------------
# Canonical daily-summary selection helpers
# ---------------------------------------------------------------------------

_COMMITTED_RUN_STATUSES = frozenset({"COMPLETE", "DEGRADED"})


def _manifest_is_committed(run: dict[str, Any]) -> bool:
    """
    Return True only when the canonical run is safe to expose as a summary.

    Header finalization happens before row persistence, so finished_at alone is
    insufficient.  A committed manifest must also have a successful exact
    reconciliation proof and the persisted row count must equal the discovered
    count.
    """
    reconciliation = run.get("reconciliation")
    if isinstance(reconciliation, str):
        try:
            reconciliation = json.loads(reconciliation)
        except Exception:
            reconciliation = None

    try:
        total_discovered = int(run.get("total_discovered", -1))
        persisted_rows = int(run.get("persisted_row_count", -2))
    except (TypeError, ValueError):
        return False

    return bool(
        run.get("finished_at")
        and run.get("run_status") in _COMMITTED_RUN_STATUSES
        and isinstance(reconciliation, dict)
        and reconciliation.get("reconciled") is True
        and persisted_rows == total_discovered
    )


def get_latest_committed_run(run_date: str) -> dict | None:
    """
    Return the latest fully committed/reconciled canonical run for a date.

    Database failures are intentionally allowed to propagate.  A query failure
    is not proof that no canonical run exists, so silently falling back to the
    legacy store would violate the single-source selection contract.
    """
    conn = _get_conn()
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT r.*,
                       (
                           SELECT COUNT(*)
                           FROM wow_daily_run_rows rr
                           WHERE rr.run_id = r.run_id
                       ) AS persisted_row_count
                FROM wow_daily_runs r
                WHERE r.run_date = %s
                  AND r.finished_at IS NOT NULL
                  AND r.run_status IN ('COMPLETE', 'DEGRADED')
                  AND COALESCE(
                      (r.reconciliation->>'reconciled')::boolean,
                      FALSE
                  ) = TRUE
                  AND (
                      SELECT COUNT(*)
                      FROM wow_daily_run_rows rr
                      WHERE rr.run_id = r.run_id
                  ) = r.total_discovered
                ORDER BY r.finished_at DESC, r.started_at DESC
                LIMIT 1
                """,
                (run_date,),
            )
            cols = [d[0] for d in cur.description]
            candidates = [dict(zip(cols, row)) for row in cur.fetchall()]
    finally:
        conn.close()

    for run in candidates:
        for key in (
            "requested_sports", "scanned_sports", "missing_sports",
            "failed_modules", "runtime_provenance", "source_union_counts",
            "reconciliation",
        ):
            if isinstance(run.get(key), str):
                try:
                    run[key] = json.loads(run[key])
                except Exception:
                    pass
        if _manifest_is_committed(run):
            return run
    return None


def get_run_summary_counts(run_id: str) -> dict[str, int]:
    """Return count-by-classification for one canonical run."""
    conn = _get_conn()
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT classification, COUNT(*) AS cnt
            FROM wow_daily_run_rows
            WHERE run_id = %s
            GROUP BY classification
            ORDER BY cnt DESC
            """,
            (run_id,),
        )
        rows = cur.fetchall()
    conn.close()
    return {
        classification: int(count)
        for classification, count in rows
        if classification is not None
    }


def get_run_summary_rows(
    run_id: str,
    *,
    category: str | None = None,
    sport: str | None = None,
    limit: int = 80,
    offset: int = 0,
) -> list[dict]:
    """
    Return canonical run rows in the legacy compact-row input shape.

    full_row preserves the established scan summary fields; immutable manifest
    columns overwrite identity/classification fields so the manifest remains
    authoritative if the embedded row differs.
    """
    conn = _get_conn()
    params: list[Any] = [run_id]
    category_sql = ""
    if category:
        category_sql = "AND classification = %s"
        params.append(category)
    sport_sql = ""
    if sport:
        sport_sql = "AND sport = %s"
        params.append(sport.upper())
    params.extend((limit, offset))

    with conn.cursor() as cur:
        cur.execute(
            f"""
            SELECT sport, player, prop, side, line, game_date,
                   terminal_bucket, classification, wow_score,
                   final_approval_blocker, audit_valid, side_resolution,
                   reconciliation_status, full_row
            FROM wow_daily_run_rows
            WHERE run_id = %s
              {category_sql}
              {sport_sql}
            ORDER BY wow_score DESC NULLS LAST, sport, player, prop, side
            LIMIT %s
            OFFSET %s
            """,
            params,
        )
        cols = [d[0] for d in cur.description]
        stored_rows = [dict(zip(cols, row)) for row in cur.fetchall()]
    conn.close()

    output: list[dict] = []
    manifest_fields = (
        "sport", "player", "prop", "side", "line", "game_date",
        "terminal_bucket", "classification", "wow_score",
        "final_approval_blocker", "audit_valid", "side_resolution",
        "reconciliation_status",
    )
    for stored in stored_rows:
        full_row = stored.get("full_row")
        if isinstance(full_row, str):
            try:
                full_row = json.loads(full_row)
            except Exception:
                full_row = {}
        row = dict(full_row) if isinstance(full_row, dict) else {}
        for field_name in manifest_fields:
            row[field_name] = stored.get(field_name)
        output.append(row)
    return output


def get_run_source_flags(run_id: str) -> dict[str, Any]:
    """Aggregate legacy-compatible source/audit flags for a canonical run."""
    conn = _get_conn()
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT
                COUNT(*) AS total,
                COUNT(*) FILTER (
                    WHERE COALESCE(full_row->>'source_odds', '') LIKE '%%AVAILABLE%%'
                ) AS odds_avail,
                COUNT(*) FILTER (
                    WHERE COALESCE(full_row->>'source_odds', '') NOT IN ('NOT_CALLED', '')
                ) AS odds_called,
                COUNT(*) FILTER (
                    WHERE COALESCE(full_row->>'source_logs', '') LIKE '%%AVAILABLE%%'
                ) AS logs_avail,
                COUNT(*) FILTER (
                    WHERE COALESCE(full_row->>'source_logs', '') NOT IN ('NOT_CALLED', '')
                ) AS logs_called,
                COUNT(*) FILTER (
                    WHERE COALESCE(full_row->>'source_status', '') LIKE '%%AVAILABLE%%'
                ) AS status_avail,
                COUNT(*) FILTER (
                    WHERE COALESCE(full_row->>'source_status', '') NOT IN ('NOT_CALLED', '')
                ) AS status_called,
                COUNT(*) FILTER (
                    WHERE COALESCE(full_row->>'source_rundown', '') LIKE '%%AVAILABLE%%'
                ) AS rundown_avail,
                COUNT(*) FILTER (WHERE audit_valid = TRUE) AS audit_valid_count,
                COUNT(*) FILTER (WHERE audit_valid = FALSE) AS audit_invalid_count,
                COUNT(*) FILTER (
                    WHERE COALESCE(full_row->>'projection_status', '') = 'INTERNAL'
                ) AS internal_proj_count,
                COUNT(*) FILTER (
                    WHERE COALESCE(full_row->>'projection_status', '') = 'EXTERNAL'
                ) AS external_proj_count,
                COUNT(*) FILTER (
                    WHERE COALESCE(full_row->>'projection_status', '') = 'MISSING'
                ) AS missing_proj_count,
                ARRAY_AGG(DISTINCT sport) AS sports
            FROM wow_daily_run_rows
            WHERE run_id = %s
            """,
            (run_id,),
        )
        cols = [d[0] for d in cur.description]
        stored = cur.fetchone()
    conn.close()
    return dict(zip(cols, stored)) if stored else {}
