"""
storage/daily_manifest.py — Immutable WOW Daily Run Manifest

Provides persistent, idempotent storage for canonical WOW Daily run records.

Tables
------
wow_daily_runs        — one row per canonical daily run (run_id PK)
wow_daily_run_rows    — one row per evaluated selection in a run

Design invariants
-----------------
- run_id is a UUID generated by the orchestrator before any evaluation begins.
- Rows are written once, never updated.  Reconciliation state is appended-only.
- A duplicate run_id write is an idempotent no-op (ON CONFLICT DO NOTHING).
- No selection write succeeds without a matching run header.
- can_execute = False (dry-run module; actual writes are driven by the route).
"""
from __future__ import annotations

import json
import os
import logging
from datetime import date, datetime, timezone
from typing import Any

import psycopg2

logger = logging.getLogger(__name__)

can_execute = False
MODULE_ID = "WOW-DAILY-MANIFEST-v1.0"

# ---------------------------------------------------------------------------
# DB connection helper (mirrors storage/results.py pattern)
# ---------------------------------------------------------------------------

def _get_conn():
    url = os.environ.get("DATABASE_URL", "")
    if not url:
        raise RuntimeError("DATABASE_URL not set")
    return psycopg2.connect(url)


# ---------------------------------------------------------------------------
# Schema bootstrap
# ---------------------------------------------------------------------------

_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS wow_daily_runs (
    run_id              TEXT PRIMARY KEY,
    run_date            DATE        NOT NULL,
    started_at          TIMESTAMPTZ NOT NULL,
    finished_at         TIMESTAMPTZ,
    environment         TEXT        NOT NULL DEFAULT 'live',
    requested_sports    JSONB       NOT NULL DEFAULT '[]',
    scanned_sports      JSONB       NOT NULL DEFAULT '[]',
    missing_sports      JSONB       NOT NULL DEFAULT '[]',
    run_status          TEXT        NOT NULL DEFAULT 'IN_PROGRESS',
    failed_modules      JSONB       NOT NULL DEFAULT '[]',
    runtime_provenance  JSONB,
    source_union_counts JSONB,
    total_discovered    INTEGER     NOT NULL DEFAULT 0,
    reconciliation      JSONB,
    session_id          TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS wow_daily_run_rows (
    id                      SERIAL PRIMARY KEY,
    run_id                  TEXT        NOT NULL REFERENCES wow_daily_runs(run_id),
    canonical_selection_id  TEXT        NOT NULL,
    market_version_id       TEXT,
    run_date                DATE        NOT NULL,
    sport                   TEXT        NOT NULL,
    player                  TEXT        NOT NULL,
    prop                    TEXT        NOT NULL,
    side                    TEXT        NOT NULL,
    line                    REAL        NOT NULL,
    game_date               TEXT,
    terminal_bucket         TEXT,
    classification          TEXT,
    wow_score               REAL,
    final_approval_blocker  TEXT,
    audit_valid             BOOLEAN,
    side_resolution         TEXT,
    reconciliation_status   TEXT,
    full_row                JSONB,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (run_id, canonical_selection_id)
);

CREATE INDEX IF NOT EXISTS idx_wow_daily_runs_date ON wow_daily_runs(run_date);
CREATE INDEX IF NOT EXISTS idx_wow_daily_run_rows_run_id ON wow_daily_run_rows(run_id);
CREATE INDEX IF NOT EXISTS idx_wow_daily_run_rows_sel_id ON wow_daily_run_rows(canonical_selection_id);
"""


def ensure_tables() -> bool:
    """Create manifest tables if they don't exist. Returns True on success."""
    try:
        conn = _get_conn()
        with conn:
            with conn.cursor() as cur:
                cur.execute(_SCHEMA_SQL)
        conn.close()
        return True
    except Exception as exc:
        logger.error("daily_manifest.ensure_tables failed: %s", exc)
        return False


# ---------------------------------------------------------------------------
# Run header
# ---------------------------------------------------------------------------

def create_run(
    *,
    run_id: str,
    run_date: str,
    started_at: str,
    environment: str,
    requested_sports: list[str],
    session_id: str | None = None,
    runtime_provenance: dict | None = None,
) -> bool:
    """
    Insert the run header row.  Idempotent — duplicate run_id is a no-op.
    Returns True on success, False on failure.
    """
    try:
        conn = _get_conn()
        with conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO wow_daily_runs
                        (run_id, run_date, started_at, environment,
                         requested_sports, session_id, runtime_provenance)
                    VALUES (%s, %s, %s, %s, %s, %s, %s)
                    ON CONFLICT (run_id) DO NOTHING
                    """,
                    (
                        run_id,
                        run_date,
                        started_at,
                        environment,
                        json.dumps(requested_sports),
                        session_id,
                        json.dumps(runtime_provenance) if runtime_provenance else None,
                    ),
                )
        conn.close()
        return True
    except Exception as exc:
        logger.error("daily_manifest.create_run failed for %s: %s", run_id, exc)
        return False


def finalize_run(
    *,
    run_id: str,
    finished_at: str,
    run_status: str,
    scanned_sports: list[str],
    missing_sports: list[str],
    failed_modules: list[str],
    total_discovered: int,
    source_union_counts: dict,
    reconciliation: dict,
) -> bool:
    """Update run header with final state. Called after all rows are written."""
    try:
        conn = _get_conn()
        with conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    UPDATE wow_daily_runs SET
                        finished_at         = %s,
                        run_status          = %s,
                        scanned_sports      = %s,
                        missing_sports      = %s,
                        failed_modules      = %s,
                        total_discovered    = %s,
                        source_union_counts = %s,
                        reconciliation      = %s
                    WHERE run_id = %s
                    """,
                    (
                        finished_at,
                        run_status,
                        json.dumps(scanned_sports),
                        json.dumps(missing_sports),
                        json.dumps(failed_modules),
                        total_discovered,
                        json.dumps(source_union_counts),
                        json.dumps(reconciliation),
                        run_id,
                    ),
                )
        conn.close()
        return True
    except Exception as exc:
        logger.error("daily_manifest.finalize_run failed for %s: %s", run_id, exc)
        return False


# ---------------------------------------------------------------------------
# Selection rows
# ---------------------------------------------------------------------------

def save_run_row(
    *,
    run_id: str,
    canonical_selection_id: str,
    market_version_id: str | None,
    run_date: str,
    sport: str,
    player: str,
    prop: str,
    side: str,
    line: float,
    game_date: str | None,
    terminal_bucket: str | None,
    classification: str | None,
    wow_score: float | None,
    final_approval_blocker: str | None,
    audit_valid: bool | None,
    side_resolution: str | None,
    reconciliation_status: str | None,
    full_row: dict,
) -> bool:
    """
    Persist one evaluated selection row.  Idempotent on (run_id, canonical_selection_id).
    Returns True on success.
    """
    try:
        conn = _get_conn()
        with conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO wow_daily_run_rows (
                        run_id, canonical_selection_id, market_version_id,
                        run_date, sport, player, prop, side, line, game_date,
                        terminal_bucket, classification, wow_score,
                        final_approval_blocker, audit_valid, side_resolution,
                        reconciliation_status, full_row
                    ) VALUES (
                        %s, %s, %s,
                        %s, %s, %s, %s, %s, %s, %s,
                        %s, %s, %s,
                        %s, %s, %s,
                        %s, %s
                    )
                    ON CONFLICT (run_id, canonical_selection_id) DO NOTHING
                    """,
                    (
                        run_id, canonical_selection_id, market_version_id,
                        run_date, sport, player, prop, side, line, game_date,
                        terminal_bucket, classification, wow_score,
                        final_approval_blocker, audit_valid, side_resolution,
                        reconciliation_status, json.dumps(full_row, default=str),
                    ),
                )
        conn.close()
        return True
    except Exception as exc:
        logger.error(
            "daily_manifest.save_run_row failed run=%s sel=%s: %s",
            run_id, canonical_selection_id, exc,
        )
        return False


# ---------------------------------------------------------------------------
# Read helpers
# ---------------------------------------------------------------------------

def get_run(run_id: str) -> dict | None:
    """Fetch run header by run_id. Returns None when not found."""
    try:
        conn = _get_conn()
        with conn.cursor() as cur:
            cur.execute(
                "SELECT * FROM wow_daily_runs WHERE run_id = %s LIMIT 1",
                (run_id,),
            )
            cols = [d[0] for d in cur.description]
            row = cur.fetchone()
        conn.close()
        if row is None:
            return None
        result = dict(zip(cols, row))
        for k in ("requested_sports", "scanned_sports", "missing_sports",
                  "failed_modules", "runtime_provenance", "source_union_counts",
                  "reconciliation"):
            if isinstance(result.get(k), str):
                try:
                    result[k] = json.loads(result[k])
                except Exception:
                    pass
        return result
    except Exception as exc:
        logger.error("daily_manifest.get_run failed for %s: %s", run_id, exc)
        return None


def get_run_rows(run_id: str, limit: int = 500) -> list[dict]:
    """Fetch all evaluated rows for a run. Returns [] on failure."""
    try:
        conn = _get_conn()
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT run_id, canonical_selection_id, market_version_id,
                       sport, player, prop, side, line, game_date,
                       terminal_bucket, classification, wow_score,
                       final_approval_blocker, audit_valid, side_resolution,
                       reconciliation_status, created_at
                FROM wow_daily_run_rows
                WHERE run_id = %s
                ORDER BY sport, player, prop, side
                LIMIT %s
                """,
                (run_id, limit),
            )
            cols = [d[0] for d in cur.description]
            rows = [dict(zip(cols, r)) for r in cur.fetchall()]
        conn.close()
        return rows
    except Exception as exc:
        logger.error("daily_manifest.get_run_rows failed for %s: %s", run_id, exc)
        return []


def list_runs(run_date: str | None = None, limit: int = 10) -> list[dict]:
    """List recent run headers. Optionally filter by date."""
    try:
        conn = _get_conn()
        with conn.cursor() as cur:
            if run_date:
                cur.execute(
                    """
                    SELECT run_id, run_date, started_at, finished_at,
                           environment, run_status, total_discovered,
                           requested_sports, scanned_sports, missing_sports
                    FROM wow_daily_runs
                    WHERE run_date = %s
                    ORDER BY started_at DESC LIMIT %s
                    """,
                    (run_date, limit),
                )
            else:
                cur.execute(
                    """
                    SELECT run_id, run_date, started_at, finished_at,
                           environment, run_status, total_discovered,
                           requested_sports, scanned_sports, missing_sports
                    FROM wow_daily_runs
                    ORDER BY started_at DESC LIMIT %s
                    """,
                    (limit,),
                )
            cols = [d[0] for d in cur.description]
            rows = [dict(zip(cols, r)) for r in cur.fetchall()]
        conn.close()
        for r in rows:
            for k in ("requested_sports", "scanned_sports", "missing_sports"):
                if isinstance(r.get(k), str):
                    try:
                        r[k] = json.loads(r[k])
                    except Exception:
                        pass
        return rows
    except Exception as exc:
        logger.error("daily_manifest.list_runs failed: %s", exc)
        return []
